name: Feature Request
description: Request a feature
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this feature request.
- type: textarea
  id: feature-request
  attributes:
    label: Feature Request
    description: Please describe your feature request. The more detailed you can be, the better. You can upload any screenshots here as well (but please do not upload images of the mascot). Please only use this Feature Request report for actual features. Do not use this report to request to make it work with a specific website.
    placeholder: Describe your feature request
  validations:
    required: true
- type: checkboxes
  id: adherence
  attributes:
    label: Adherence
    description: Feature requests should be about actual features that can be added into the app. Please check this to confirm that your feature request is an actual feature and isn't asking how (or requesting) to make it work with a specific website.
    options:
      - label: My feature request is an actual feature and is not related to making it work with a specific website
        required: true
  validations:
    required: true
